/* ============================================================
   ForceGraph — reusable neo4j-style d3 force-directed graph.
   Renders any { nodes:[{id,cat}], links:[{source,target,rel}],
   cats:{cat:{c,label}} } dataset. Layout is generated by the
   simulation, auto-fits on settle. Used by the standalone
   Group-ontology screen and the BRD "Decision Graph" toggle.
   ============================================================ */
(function () {
  const UI = (window.UI = window.UI || {});
  const { Eyebrow, Button, Icon, Badge, Stroke } = UI;

  // Split a label into up to two balanced lines so it fits inside a node.
  function caption(id) {
    if (id.length <= 7) return [id];
    if (id.indexOf(" ") !== -1) {
      const w = id.split(" ");
      if (w.length === 1) return [id];
      let best = 1, diff = 1e9;
      for (let i = 1; i < w.length; i++) {
        const a = w.slice(0, i).join(" ").length, b = w.slice(i).join(" ").length;
        if (Math.abs(a - b) < diff) { diff = Math.abs(a - b); best = i; }
      }
      return [w.slice(0, best).join(" "), w.slice(best).join(" ")];
    }
    const parts = id.replace(/([a-z])([A-Z])/g, "$1\u0000$2").split("\u0000");
    if (parts.length === 1) return [id];
    return [parts[0], parts.slice(1).join("")];
  }

  function ForceGraph({ data, height = 580, radius = 35, dense = false, highlight = null, highlightOn = false, onToggleHighlight }) {
    const ref = React.useRef(null);
    const [seed, setSeed] = React.useState(0);

    React.useEffect(() => {
      const d3 = window.d3;
      const el = ref.current;
      if (!d3 || !el || !data) return;
      const CATS = data.cats;
      const R = radius;
      const width = el.clientWidth || 1080;

      d3.select(el).selectAll("*").remove();
      const svg = d3.select(el).append("svg")
        .attr("width", width).attr("height", height).attr("viewBox", [0, 0, width, height]);

      const defs = svg.append("defs");

      const root = svg.append("g");
      const zoom = d3.zoom().scaleExtent([0.35, 2.6]).on("zoom", (e) => root.attr("transform", e.transform));
      svg.call(zoom);

      const nodes = data.nodes.map(d => ({ ...d }));
      const links = data.links.map(d => ({ ...d }));
      nodes.forEach(n => {
        n.x = width / 2 + (Math.random() - 0.5) * width * 0.7;
        n.y = height / 2 + (Math.random() - 0.5) * height * 0.7;
      });

      const adj = {};
      data.nodes.forEach(n => (adj[n.id] = new Set([n.id])));
      data.links.forEach(l => { adj[l.source].add(l.target); adj[l.target].add(l.source); });

      // degree → Obsidian-style node sizing
      const deg = {};
      data.nodes.forEach(n => (deg[n.id] = 0));
      data.links.forEach(l => { deg[l.source] = (deg[l.source] || 0) + 1; deg[l.target] = (deg[l.target] || 0) + 1; });
      const nodeR = d => Math.max(4.5, Math.min(15, 4.5 + (deg[d.id] || 0) * 1.5));
      const MAXR = 15;

      // use-case pathway highlight
      const HI = (highlight && highlightOn) ? new Set(highlight.nodes) : null;
      const FOCUS = "#FF462D";
      const lid = (v) => (typeof v === "object" ? v.id : v);
      const linkOnPath = (l) => HI && HI.has(lid(l.source)) && HI.has(lid(l.target));

      // gentle spline (quadratic) connector
      function linkPath(d) {
        const sx = d.source.x, sy = d.source.y, tx = d.target.x, ty = d.target.y;
        const dx = tx - sx, dy = ty - sy, L = Math.hypot(dx, dy) || 1;
        const off = Math.min(46, L * 0.14);
        const cx = (sx + tx) / 2 - (dy / L) * off, cy = (sy + ty) / 2 + (dx / L) * off;
        return `M${sx},${sy} Q${cx},${cy} ${tx},${ty}`;
      }

      const linkSel = root.append("g").attr("fill", "none").attr("stroke", "#cbd5e1").attr("stroke-width", 1.1).attr("stroke-opacity", 0.5)
        .selectAll("path").data(links).join("path").attr("class", "fg-link");

      const labelSel = root.append("g").selectAll("g.fg-rel").data(links).join("g").attr("class", "fg-rel");
      labelSel.append("rect").attr("rx", 4).attr("fill", "#fff").attr("opacity", 0.92);
      labelSel.append("text").attr("class", "fg-rel-t").attr("text-anchor", "middle").attr("dy", "0.32em").text(d => d.rel);
      labelSel.selectAll("rect").each(function () {
        const t = this.parentNode.querySelector("text"); const bb = t.getBBox();
        d3.select(this).attr("x", bb.x - 3).attr("y", bb.y - 1).attr("width", bb.width + 6).attr("height", bb.height + 2);
      });
      labelSel.style("opacity", 0); // Obsidian: edge labels surface on hover only

      const nodeSel = root.append("g").selectAll("g.fg-node").data(nodes).join("g").attr("class", "fg-node").style("cursor", "grab");
      // soft glow halo (revealed on hover)
      nodeSel.append("circle").attr("class", "fg-glow").attr("r", d => nodeR(d) + 8).attr("fill", d => CATS[d.cat].c).attr("opacity", 0);
      // use-case focus ring (path nodes)
      nodeSel.append("circle").attr("class", "fg-focus").attr("r", d => nodeR(d) + 5).attr("fill", "none").attr("stroke", FOCUS).attr("stroke-width", 2).attr("opacity", 0);
      // decision states → dashed ring; final states → faint ring
      nodeSel.filter(d => d.type === "decision").append("circle").attr("r", d => nodeR(d) + 4).attr("fill", "none")
        .attr("stroke", d => CATS[d.cat].c).attr("stroke-width", 1).attr("stroke-dasharray", "2 2").attr("opacity", 0.6);
      nodeSel.filter(d => d.type === "final").append("circle").attr("r", d => nodeR(d) + 3).attr("fill", "none")
        .attr("stroke", d => CATS[d.cat].c).attr("stroke-width", 1).attr("opacity", 0.45);
      // the dot
      nodeSel.append("circle").attr("class", "fg-dot").attr("r", nodeR).attr("fill", d => CATS[d.cat].c).attr("stroke", "#fff").attr("stroke-width", 1.6);
      nodeSel.append("title").text(d => d.id + (d.type ? " · " + d.type : ""));
      // label below the dot, with a halo for legibility
      nodeSel.append("text").attr("class", "fg-lab").attr("text-anchor", "middle").attr("y", d => nodeR(d) + 11)
        .attr("font-family", "var(--font-sans)").attr("font-size", d => (deg[d.id] > 4 ? 10 : 9)).attr("font-weight", 500)
        .attr("fill", "#475569").attr("paint-order", "stroke").attr("stroke", "#fbfcfd").attr("stroke-width", 3.5).attr("stroke-linejoin", "round")
        .attr("pointer-events", "none").text(d => d.label || d.id);

      nodeSel.on("mouseover", function (e, d) {
        const near = adj[d.id];
        nodeSel.style("opacity", o => near.has(o.id) ? 1 : 0.14);
        nodeSel.selectAll(".fg-glow").attr("opacity", o => near.has(o.id) ? 0.22 : 0);
        linkSel.attr("stroke", l => (l.source.id === d.id || l.target.id === d.id) ? CATS[d.cat].c : "#cbd5e1")
          .attr("stroke-opacity", l => (l.source.id === d.id || l.target.id === d.id) ? 0.85 : 0.05)
          .attr("stroke-width", l => (l.source.id === d.id || l.target.id === d.id) ? 1.8 : 1.1);
        labelSel.style("opacity", l => (l.source.id === d.id || l.target.id === d.id) ? 1 : 0);
      }).on("mouseout", function () {
        nodeSel.selectAll(".fg-glow").attr("opacity", 0);
        applyBase();
      });

      // base styling — reflects the use-case pathway highlight (or plain)
      function applyBase() {
        nodeSel.style("opacity", d => HI ? (HI.has(d.id) ? 1 : 0.4) : 1);
        nodeSel.selectAll(".fg-focus").attr("opacity", d => (HI && HI.has(d.id)) ? 0.32 : 0);
        linkSel.attr("stroke", l => linkOnPath(l) ? FOCUS : "#cbd5e1")
          .attr("stroke-opacity", l => HI ? (linkOnPath(l) ? 0.5 : 0.18) : 0.5)
          .attr("stroke-width", l => linkOnPath(l) ? 1.6 : 1.1);
        labelSel.style("opacity", l => (HI && linkOnPath(l)) ? 0.85 : 0);
      }
      applyBase();

      const linkDist = dense ? 78 : 100;
      const charge = dense ? -420 : -520;
      const sim = d3.forceSimulation(nodes)
        .force("link", d3.forceLink(links).id(d => d.id).distance(linkDist).strength(0.4))
        .force("charge", d3.forceManyBody().strength(charge))
        .force("center", d3.forceCenter(width / 2, height / 2))
        .force("collide", d3.forceCollide().radius(d => nodeR(d) + 22))
        .force("x", d3.forceX(width / 2).strength(0.05))
        .force("y", d3.forceY(height / 2).strength(0.07))
        .on("tick", ticked);

      nodeSel.call(d3.drag()
        .on("start", (e, d) => { if (!e.active) sim.alphaTarget(0.3).restart(); d.fx = d.x; d.fy = d.y; })
        .on("drag", (e, d) => { d.fx = e.x; d.fy = e.y; })
        .on("end", (e, d) => { if (!e.active) sim.alphaTarget(0); d.fx = null; d.fy = null; }));

      function ticked() {
        linkSel.attr("d", linkPath);
        labelSel.attr("transform", d => `translate(${(d.source.x + d.target.x) / 2},${(d.source.y + d.target.y) / 2})`);
        nodeSel.attr("transform", d => `translate(${d.x},${d.y})`);
      }

      function fit() {
        const xs = nodes.map(n => n.x), ys = nodes.map(n => n.y);
        const minX = Math.min(...xs) - MAXR, maxX = Math.max(...xs) + MAXR, minY = Math.min(...ys) - MAXR, maxY = Math.max(...ys) + MAXR;
        const w = maxX - minX, h = maxY - minY, pad = 60;
        const scale = Math.min((width - pad * 2) / w, (height - pad * 2) / h, 1.5);
        const tx = (width - scale * (minX + maxX)) / 2, ty = (height - scale * (minY + maxY)) / 2;
        svg.transition().duration(550).call(zoom.transform, d3.zoomIdentity.translate(tx, ty).scale(scale));
      }
      sim.on("end", fit);
      const fitT = setTimeout(fit, 2400);

      return () => { clearTimeout(fitT); sim.stop(); };
    }, [seed, data, height, radius, dense, highlight, highlightOn]);

    return (
      <React.Fragment>
        <div className="onto-bar">
          <span className="onto-hint"><Icon name="information" size={13} /> Drag a node · scroll to zoom · hover to isolate a neighbourhood</span>
          <div className="onto-actions">
            {highlight && (
              <button className={`onto-hl ${highlightOn ? "on" : ""}`} onClick={onToggleHighlight} title={highlight.label}>
                <span className="dot" /> {highlightOn ? "Use-case pathway on" : "Highlight use-case"}
              </button>
            )}
            <Button variant="ghost" icon="network" onClick={() => setSeed(s => s + 1)}>Regenerate layout</Button>
          </div>
        </div>
        <div className="onto-canvas" ref={ref} style={{ height }} />
      </React.Fragment>
    );
  }
  UI.ForceGraph = ForceGraph;

  function GraphLegend({ cats, src }) {
    return (
      <div className="onto-legend">
        {Object.keys(cats).map(k => (
          <span className="onto-leg" key={k}><span className="sw" style={{ background: cats[k].c }} />{cats[k].label}</span>
        ))}
        {src && <span className="onto-src" style={{ marginLeft: "auto" }}><span className="ai-glyph" style={{ width: 11, height: 11 }} /> {src}</span>}
      </div>
    );
  }
  UI.GraphLegend = GraphLegend;

  function ScreenOntology() {
    const G = window.D.ontologyGraph;
    const PATH = {
      label: "Supply disruption → Brandt covenant reroute",
      nodes: ["Feedstock", "Cracker", "Plant", "SKU", "Covenant", "Account", "Event", "AgentRun", "PolicyRule", "WritePreview", "ERPCommit", "AuditRecord"],
    };
    const chain = [
      { seq: ["Feedstock", "Cracker", "Plant", "SKU", "Covenant", "Account"], cap: "What's exposed — the supply disruption traced up to the customer covenant" },
      { seq: ["Event", "AgentRun", "PolicyRule", "WritePreview", "ERPCommit", "AuditRecord"], cap: "What the spine does — detect, check policy, stage the write, commit, and seal the audit" },
    ];
    const [hi, setHi] = React.useState(true);
    return (
      <div>
        <div className="page-head">
          <div>
            <Eyebrow tone="ai">Semantic layer · generated from the BRD</Eyebrow>
            <h1 style={{ marginTop: 6 }}>The Group ontology</h1>
            <div className="ph-sub">One modeled schema the agents reason over and every lens renders against. Entity types and their relationships are compiled from Dow's BRD, then laid out by a force simulation — the graph is generated, not hand-drawn. The pathway in focus traces the live naphtha event through the ontology.</div>
          </div>
          <div className="ph-spacer" />
          <div style={{ display: "flex", gap: 8 }}>
            <Badge tone="violet">{G.nodes.length} entity types</Badge>
            <Badge tone="spruce">{G.links.length} relationships</Badge>
          </div>
        </div>
        <div className="panel" style={{ padding: 0, overflow: "hidden" }}>
          <ForceGraph data={G} highlight={PATH} highlightOn={hi} onToggleHighlight={() => setHi(v => !v)} />
          <GraphLegend cats={G.cats} src="d3-force layout · compiled from DOW-BRD-SC-EU-v3.1" />
          {hi && (
            <div className="onto-path">
              <div className="op-head"><span className="op-dot" /> Pathway in focus · <strong>{PATH.label}</strong></div>
              {chain.map((c, i) => (
                <div className="op-row" key={i}>
                  <div className="op-seq">
                    {c.seq.map((n, j) => (
                      <React.Fragment key={n}>
                        <span className="op-node">{n}</span>
                        {j < c.seq.length - 1 && <Stroke className="op-arr" size={13} sw={2.2} children={<polyline points="9 6 15 12 9 18" />} />}
                      </React.Fragment>
                    ))}
                  </div>
                  <div className="op-cap">{c.cap}</div>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="spine-eyebrow" style={{ marginTop: 24 }}>
          <span className="se-l">Supply hierarchy · dendrogram</span>
          <span className="se-r">The same entities as a containment tree — plant → cracker · product family → SKU · covenant customer. The hierarchy the ontology resolves to.</span>
        </div>
        <div className="panel" style={{ padding: "18px 20px" }}>
          <UI.Dendrogram data={window.D.supplyHierarchy} height={300} />
          <div className="onto-legend" style={{ borderTop: "1px solid var(--k-cool-gray-10)", marginTop: 8, paddingTop: 12 }}>
            <span className="onto-leg"><span className="sw" style={{ background: "#FF462D" }} />Plant</span>
            <span className="onto-leg"><span className="sw" style={{ background: "#9A6500" }} />Cracker</span>
            <span className="onto-leg"><span className="sw" style={{ background: "#6B36A8" }} />Product family</span>
            <span className="onto-leg"><span className="sw" style={{ background: "#29707A" }} />SKU</span>
            <span className="onto-leg"><span className="sw" style={{ background: "#2A6FDB" }} />Covenant customer</span>
          </div>
        </div>
      </div>
    );
  }
  UI.ScreenOntology = ScreenOntology;
})();
